### ISSUE TITLE
No module named 'PIL'

### ISSUE THREAD

**Issue by brmoda** [huntergregal/PNG-IDAT-Payload-Generator#6]
Traceback (most recent call last):
  File "generate.py", line 14, in <module>
    from idat import bypass_filters, save_image, verify
  File "/root/PNG-IDAT-Payload-Generator/idat.py", line 3, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'

**Comment by huntergregal** [comment]
https://stackoverflow.com/questions/8863917/importerror-no-module-named-pil

see if this link helps with your issue
